name: tcc_app
description: Aplicativo do TCC integrado ao sistema em PHP/MySQL.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Pacote para tradução dos componentes nativos do Flutter
  flutter_localizations:
    sdk: flutter

  # Ícones padrão do iOS
  cupertino_icons: ^1.0.8
  # Para fazer as chamadas à nossa API PHP
  http: ^1.2.2
  # Para armazenamento seguro de dados (token, user_id)
  flutter_secure_storage: ^9.0.0
  # Para formatação de datas e horas
  intl: ^0.20.2
  # Para o banco de dados local
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Ferramentas de análise de código
  flutter_lints: ^4.0.0
  # Ferramenta para gerar os ícones do app
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Declaração das pastas de assets (imagens, ícones, fontes)
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

# Configuração para o pacote que gera os ícones do aplicativo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"